services:
  - type: web
    name: vocab-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GH_TOKEN
        sync: false
      - key: GH_REPO
        value: SctrlB/vocab-backend
      - key: STATE_PATH
        value: data/state.json
